apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourcegraph-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: PGDATABASE
          value: postgres
        - name: PGHOST
          value: sourcegraph-postgres-stolon-proxy.sourcegraph-postgres.svc.cluster.local
        - name: PGPORT
          value: "5432"
        - name: PGSSLMODE
          value: disable
        - name: PGUSER
          value: stolon
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: sourcegraph-postgres
              key: password
        - name: CODEINTEL_PGDATABASE
          value: codeintel
        - name: CODEINTEL_PGHOST
          value: sourcegraph-postgres-stolon-proxy.sourcegraph-postgres.svc.cluster.local
        - name: CODEINTEL_PGPORT
          value: "5432"
        - name: CODEINTEL_PGSSLMODE
          value: disable
        - name: CODEINTEL_PGUSER
          value: stolon
        - name: CODEINTEL_PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: sourcegraph-postgres
              key: password