apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-proxy
spec:
  template:
    spec:
      containers:
      - name: github-proxy
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 100m
            memory: 250M
      - name: jaeger-agent
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M