apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  volumeClaimTemplates:
  - metadata:
      name: repos
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # The size of disk used to mirror your git repositories.
          # If you change this, also change indexed-search's disk size.
          storage: 400Gi
      storageClassName: sourcegraph-storage-class
  