apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitserver
spec:
  template:
    spec:
      containers:
      - name: gitserver
        resources:
          limits:
            cpu: "4"
            memory: 8G
          requests:
            cpu: "4" 
            memory: 8G
      - name: jaeger-agent
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M