apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  volumeClaimTemplates:
  - metadata:
      name: grafana-data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: sourcegraph-storage-class
  