apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexed-search
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: zoekt-webserver
        resources:
          limits:
            cpu: "3"
            memory: 16G
          requests:
            cpu: "2"
            memory: 16G
      - name: zoekt-indexserver
        resources:
          # zoekt-indexserver is CPU bound. The more CPU you allocate to it, the
          # lower lag between a new commit and it being indexed for search.
          limits:
            cpu: "8"
            memory: 16G
          requests:
            cpu: "4"
            memory: 8G
