apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  template:
    spec:
      containers:
      - name: jaeger
        resources:
          limits:
            cpu: 1
            memory: 1G
          requests:
            cpu: 500m
            memory: 500M