apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
spec:
  template:
    spec:
      containers:
      - name: pgsql
        resources:
          limits:
            cpu: "4"
            memory: 2Gi
          requests:
            cpu: "4"
            memory: 2Gi
      - name: pgsql-exporter
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi