apiVersion: apps/v1
kind: Deployment
metadata:
  name: precise-code-intel-bundle-manager
spec:
  template:
    spec:
      containers:
      - name: precise-code-intel-bundle-manager
        resources:
          limits:
            cpu: "2"
            memory: 2G
          requests:
            cpu: 500m
            memory: 500M