apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: prometheus
        # Prometheus is relied upon to monitor services for sending alerts to site admins when
        # something is wrong with Sourcegraph, thus its memory requests and limits are the same to
        # guarantee it has enough memory to perform its job reliably and prevent conflicts with
        # other pods on the same host node.
        #
        # Its average memory usage may be much lower than 3G if Sourcegraph itself does not have
        # much traffic, the 3G number chosen here is what works reliably on Sourcegraph.com with
        # lots of traffic.
        resources:
          limits:
            cpu: "2"
            memory: 8G
          requests:
            cpu: 500m
            memory: 8G