apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-runner
spec:
  template:
    spec:
      containers:
      - name: query-runner
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
      - name: jaeger-agent
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M