apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-store
spec:
  template:
    spec:
      containers:
      - name: redis-store
        resources:
          limits:
            cpu: "1"
            memory: 6Gi
          requests:
            cpu: "1"
            memory: 6Gi
      - name: redis-exporter
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi