apiVersion: apps/v1
kind: Deployment
metadata:
  name: replacer
spec:
  template:
    spec:
      containers:
      - name: replacer
        resources:
          limits:
            cpu: "4"
            memory: 500M
          requests:
            cpu: "0.5"
            memory: 500M
      - name: jaeger-agent
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M