apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcher
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: searcher
        resources:
          limits:
            cpu: "2"
            memory: 4G
          requests:
            cpu: "0.5"
            memory: 1G
      - name: jaeger-agent
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M