apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcher
spec:
  template:
    spec:
      containers:
      - name: searcher
        resources:
          limits:
            cpu: "2"
            memory: 2G
          requests:
            cpu: 500m
            memory: 500M
      - name: jaeger-agent
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M